// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_fatima.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmaQVweI7Te7pliQcm6EoZN7vma_cYdRs',
    appId: '1:1030139180435:web:3bffa443443ddda952a466',
    messagingSenderId: '1030139180435',
    projectId: 'club-fatima',
    authDomain: 'club-fatima.firebaseapp.com',
    storageBucket: 'club-fatima.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQkHgV0AcZMDUR9byUi5Ae6OFpGh9GYYw',
    appId: '1:1030139180435:android:6b51c7e3b6cb1da752a466',
    messagingSenderId: '1030139180435',
    projectId: 'club-fatima',
    storageBucket: 'club-fatima.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZDeQHobLTwWESpmNnrc1QQjbsREZ23FQ',
    appId: '1:1030139180435:ios:cf3e8513682b481052a466',
    messagingSenderId: '1030139180435',
    projectId: 'club-fatima',
    storageBucket: 'club-fatima.firebasestorage.app',
    iosBundleId: 'com.example.clubesAppBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZDeQHobLTwWESpmNnrc1QQjbsREZ23FQ',
    appId: '1:1030139180435:ios:cf3e8513682b481052a466',
    messagingSenderId: '1030139180435',
    projectId: 'club-fatima',
    storageBucket: 'club-fatima.firebasestorage.app',
    iosBundleId: 'com.example.clubesAppBase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmaQVweI7Te7pliQcm6EoZN7vma_cYdRs',
    appId: '1:1030139180435:web:131ab82f0906a74352a466',
    messagingSenderId: '1030139180435',
    projectId: 'club-fatima',
    authDomain: 'club-fatima.firebaseapp.com',
    storageBucket: 'club-fatima.firebasestorage.app',
  );
}
