// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhp7y_cCcpWFNYtsA-rgJOFMEtu9bbKL8',
    appId: '1:209153364414:web:577a5a096eb898a8d129ef',
    messagingSenderId: '209153364414',
    projectId: 'club-guemes-2',
    authDomain: 'club-guemes-2.firebaseapp.com',
    storageBucket: 'club-guemes-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvV_LrwQmthHh7uTIuGr74ieTCcqLleBc',
    appId: '1:209153364414:android:be49070caf61d4ddd129ef',
    messagingSenderId: '209153364414',
    projectId: 'club-guemes-2',
    storageBucket: 'club-guemes-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq36_7QRSeDcX3n9BgRVyGH6HKkX96I4A',
    appId: '1:209153364414:ios:e870b6118b01f83cd129ef',
    messagingSenderId: '209153364414',
    projectId: 'club-guemes-2',
    storageBucket: 'club-guemes-2.firebasestorage.app',
    iosBundleId: 'com.example.clubesAppBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq36_7QRSeDcX3n9BgRVyGH6HKkX96I4A',
    appId: '1:209153364414:ios:e870b6118b01f83cd129ef',
    messagingSenderId: '209153364414',
    projectId: 'club-guemes-2',
    storageBucket: 'club-guemes-2.firebasestorage.app',
    iosBundleId: 'com.example.clubesAppBase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhp7y_cCcpWFNYtsA-rgJOFMEtu9bbKL8',
    appId: '1:209153364414:web:75527e8e8f94ac4ed129ef',
    messagingSenderId: '209153364414',
    projectId: 'club-guemes-2',
    authDomain: 'club-guemes-2.firebaseapp.com',
    storageBucket: 'club-guemes-2.firebasestorage.app',
  );

}