// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_laloma.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8pNawVKZoi2yDdY4peLkIYB965Hh5rYQ',
    appId: '1:337573061762:web:5a0081bc094317bb94009b',
    messagingSenderId: '337573061762',
    projectId: 'la-loma-46d7e',
    authDomain: 'la-loma-46d7e.firebaseapp.com',
    storageBucket: 'la-loma-46d7e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZfpwQOaTzqeoFgV6oz01lRW-Th92YfhI',
    appId: '1:337573061762:android:5b360ee55872104094009b',
    messagingSenderId: '337573061762',
    projectId: 'la-loma-46d7e',
    storageBucket: 'la-loma-46d7e.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFsh5jA2BBMIH0_L_WPfnvGmSbnbr_Bbk',
    appId: '1:337573061762:ios:bb240634ff39aacd94009b',
    messagingSenderId: '337573061762',
    projectId: 'la-loma-46d7e',
    storageBucket: 'la-loma-46d7e.firebasestorage.app',
    iosBundleId: 'com.example.clubesAppBase',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFsh5jA2BBMIH0_L_WPfnvGmSbnbr_Bbk',
    appId: '1:337573061762:ios:bb240634ff39aacd94009b',
    messagingSenderId: '337573061762',
    projectId: 'la-loma-46d7e',
    storageBucket: 'la-loma-46d7e.firebasestorage.app',
    iosBundleId: 'com.example.clubesAppBase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8pNawVKZoi2yDdY4peLkIYB965Hh5rYQ',
    appId: '1:337573061762:web:d473b4afb217782b94009b',
    messagingSenderId: '337573061762',
    projectId: 'la-loma-46d7e',
    authDomain: 'la-loma-46d7e.firebaseapp.com',
    storageBucket: 'la-loma-46d7e.firebasestorage.app',
  );

}