// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_generico.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQIiVwRmmG2MFmgC_HI1PIlNUswkRxpEI',
    appId: '1:1023847313810:web:12c88e02463c8f9ff0d14b',
    messagingSenderId: '1023847313810',
    projectId: 'club-generico',
    authDomain: 'club-generico.firebaseapp.com',
    storageBucket: 'club-generico.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCthWeLhAygdV8rdyCiMkXADcHLqZTDdoI',
    appId: '1:1023847313810:android:d765df0bd9de9967f0d14b',
    messagingSenderId: '1023847313810',
    projectId: 'club-generico',
    storageBucket: 'club-generico.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfILHpmr6r0NtZ3U1LbUWZe87Dg1_IdjQ',
    appId: '1:1023847313810:ios:40c61a66c6f83c57f0d14b',
    messagingSenderId: '1023847313810',
    projectId: 'club-generico',
    storageBucket: 'club-generico.firebasestorage.app',
    iosBundleId: 'com.example.clubesAppBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfILHpmr6r0NtZ3U1LbUWZe87Dg1_IdjQ',
    appId: '1:1023847313810:ios:40c61a66c6f83c57f0d14b',
    messagingSenderId: '1023847313810',
    projectId: 'club-generico',
    storageBucket: 'club-generico.firebasestorage.app',
    iosBundleId: 'com.example.clubesAppBase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQIiVwRmmG2MFmgC_HI1PIlNUswkRxpEI',
    appId: '1:1023847313810:web:2d973f306d106e10f0d14b',
    messagingSenderId: '1023847313810',
    projectId: 'club-generico',
    authDomain: 'club-generico.firebaseapp.com',
    storageBucket: 'club-generico.firebasestorage.app',
  );

}